parameters:
  jenkins:
    client:
      job:
        openstack_database_cleanup:
          type: workflow-scm
          name: openstack-database-cleanup
          display_name: "Deploy - Openstack Database Cleanup"
          discard:
            build:
              keep_num: 50
          concurrent: true
          scm:
            type: git
            url: "${_param:jenkins_gerrit_url}/mk/mk-pipelines"
            branch: "${_param:jenkins_pipelines_branch}"
            credentials: ${_param:jenkins_gerrit_credentials}
            script: openstack-database-cleanup.groovy
          param:
            SALT_MASTER_CREDENTIALS:
              type: string
              default: "salt"
            SALT_MASTER_URL:
              type: string
              default: "${_param:jenkins_salt_api_url}"
