classes:
- system.defaults.debmirror
parameters:
  debmirror:
    client:
      enabled: true
      mirrors:
        mirror_mirantis_com_update_docker_xenial:
          force: ${_param:mirror_mirantis_com_docker_xenial_force}
          lock_target: True
          extra_flags: [ '--verbose', '--progress', '--nosource', '--no-check-gpg', '--rsync-extra=none' ]
          method: "${_param:debmirror_mirrors_sync_method}"
          arch: [ 'amd64' ]
          mirror_host: "${_param:debmirror_mirrors_host}"
          mirror_root: "${_param:debmirror_mirrors_update_root}/docker/xenial/"
          target_dir: "${_param:debmirror_mirrors_update_target_dir}/docker/xenial/"
          cache_dir: "${_param:debmirror_mirrors_common_cache_dir}/docker/"
          log_file: "/var/log/debmirror/mirror_mirantis_com_update_docker_xenial.log"
          dist: [ xenial ]
          section: [ stable ]
          filter:
            # conteinerD - forked at 'extra' repo.
            001: --exclude='(docker-ce_17|containerd.io_1.2.0~(beta|rc))'
            # Drop docker-ce <= 18.09
            002: --exclude='(docker-ce(-|_)18.0[0-8])'
